### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dhled** [ScalABLE40/scxml_manager#1]
- [ ] New Documentation 

- [ ] Evaluate Performance on startup

- [ ] Evaluate Performance on big state machine

- [ ] Integration tests with qt_smach_viewer
